spring.application.name=checkout

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:db/pricing-data.sql,classpath:db/offer-data.sql